### ISSUE TITLE
Incorrect bits order

### ISSUE THREAD

**Issue by Mobivlad** [DianaDemydko/LCD_SPL#2]
You have to send 4 MSB bits at first:
https://github.com/DianaDemydko/LCD_SPL/blob/d682a279442107b142658bf584fd8934a6651484/LCD.c#L45
And then 4 LSB bits:
https://github.com/DianaDemydko/LCD_SPL/blob/d682a279442107b142658bf584fd8934a6651484/LCD.c#L39

**Comment by DianaDemydko** [comment]
Fixed
